version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
  - package-ecosystem: npm
    directory: /example
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
