language: node_js

node_js:
  - 8

services:
  - mongodb

install:
  - yarn
  - yarn --cwd ./example

script:
  - yarn test

cache:
  yarn: true
  directories:
    - node_modules
    - example/node_modules
